export const SEASONS = {
    1: 'Red War',
    2: 'Curse of Osiris',
    3: 'Warmind',
    4: 'Forsaken',
    5: 'Forge',
    6: 'Drifter',
    7: 'Opulence',
    8: 'Shadowkeep',
    9: 'Dawn',
    10: 'Worthy',
    11: 'Arrivals',
    12: 'Beyond Light',
    13: 'Chosen',
    14: 'Splicer',
    15: 'Lost',
    16: 'Witch Queen',
    17: 'Haunted',
    18: 'Plunder',
    19: 'Seraph',
    20: 'Lightfall',
    21: 'Deep',
    22: 'Witch',
    23: 'Wish',
    24: 'Final Shape',
}